### ISSUE TITLE
Rendre plus pratique l'affichage des fichiers de paramètres de publication

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#100]
Dans la colonne de droite de la vue trame, les fichiers de paramètres de publication (jobs) disponibles apparaissent dans une liste déroulante.

Cet affichage atteint ses limites quand on commence à dépasser une dizaine de fichiers. Faut-il dans ce cas plutôt prévoir l'ouverture d'un mini-explorateur ?

Si oui, il serait utile de pouvoir regrouper les fichiers dans des sous-dossiers (voire sous-sous-dossiers) de /publication-parameters

**Comment by vbdx** [comment]
Ou alors donner la possibilité de scroller pour atteindre tous les éléments

**Comment by kolekti** [comment]
on peut mettre un champ de saisie qui filtre le menu des que des caractères sont entrés et n'affiche que les noms qui contiennent la sous-chaine saisie.
J'ai peur que d'avoir systématiquement un dialogue pour la saisie déroute l'utilisateur lorsqu'il n'y a que 2 ou 3 jobs. Et proposer deux modalités différentes en fonction du nombre d'entrées ne va pas dans le sens de la simplicité de l'interface...

**Comment by vbdx** [comment]
OK pour le filtrage dynamique de la liste selon les premiers caractères saisis

**Comment by vbdx** [comment]
Quand on clique dans le champ "Filtrer la liste" elle se referme

On arrive uniquement à accéder au contenu du champ en passant par TAB   mais ensuite il ne se passe rien quand on saisit les premières lettres

**Comment by vbdx** [comment]
(observé avec Firefox 48.0)

**Comment by kolekti** [comment]
Comportement impossible a reproduire
Le champ "filtrer la liste" est automatiquement selectionné à l'ouverture du menu, nul besoin de cliquer
Un clic sur le fond du menu ferme ce dernier (comportement normal)

Peux-tu joindre une copie de la console javascript de ton navigateur apres fermeture inopinée du menu ?
