### ISSUE TITLE
Rendre plus pratique l'affichage de dizaines de valeurs de critères

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#101]
On constate sur certains projets que le nombre de valeurs pour un critère peut être élevé (plus d'une cinquantaine).

Dans ce cas leur affichage dans une liste déroulante pose problème (obligation de dézoomer fortement pour voir les valeurs du bas).

Peut-on plutôt prévoir l'ouverture d'un mini-explorateur ? Si oui, il serait utile de pouvoir regrouper visuellement les valeurs dans des sous-familles.

**Comment by vbdx** [comment]
idem #100

**Comment by kolekti** [comment]
meme solution a mettre en oeuvre que dans #100, champ de saisie pour filtrer les valeurs. Il n'y a pas dans kolekti la possibilité de déclarer/de représenter des 'familles' de valeurs.

**Comment by vbdx** [comment]
OK pour le filtrage dynamique de la liste selon les premiers caractères saisis

**Comment by vbdx** [comment]
cf #100

**Comment by vbdx** [comment]
Après la première sélection de valeur, si on veut faire une nouvelle sélection la liste qui s'affiche n'est pas complète : elle affiche le résultat de la sélection précédente au lieu d'afficher l'ensemble des valeurs
