### ISSUE TITLE
"Aucun fichier sélectionné" reste sur une ligne

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#102]
Dans l'onglet Versions, à droite du bouton "Parcourir" pour l'importation d'un assemblage traduit, le texte par défaut "Aucun fichier sélectionné" reste toujours sur une ligne même quand la fenêtre est réduite (ce qui le fait sortir du cadre)

**Comment by kolekti** [comment]
L'apparence et le libellé de ce bouton est géré par le navigateur et ne peut pas etre stylé par le css de la page qui le contient.
