### ISSUE TITLE
Avoir la possibilité de supprimer une langue dans une version

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#105]
Dans l'onglet Versions, on peut créer/initialiser une langue, par contre il n'existe de possibilité de la supprimer (si on l'a créée par erreur, ou si la traduction n'est finalement plus à faire).

Peut-on ajouter un bouton "Supprimer" (avec message de confirmation) à droite sour la zone "Télécharger" ?

**Comment by kolekti** [comment]
ok, mais du coup l'onglet de la langue reste présent dans l'interface et revient au status "non initialisé"

**Comment by vbdx** [comment]
Oui (cela ne supprime pas la langue dans le paramétrage du projet)
