### ISSUE TITLE
Accès aux logs ?

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#107]
En cas de comportement anormal (temps de traitement un peu long) ou de message d'erreur imprécis, a-t-on la possibilité de consulter les logs du serveur ?

Sont-ils enregistrés quelquepart ou bien faut-il modifier Kolekti pour que cela soit le cas ?

**Comment by kolekti** [comment]
Les logs sont dans le sous-dossier .logs du dossier des projets.
