### ISSUE TITLE
Validation d'une synchro sans commit

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#11]
Lors de la seconde étape de la synchro (Envoi des modifications vers l'arborescence distante), lorsqu'il y a des nouveaux fichiers en local que l'on ne veut pas officialiser (ex : des essais), un clic sur Valider ne produit aucun effet visible.
On devrait revenir sur la page Synchro avec le message "Le projet est partiellement synchronisé"

**Comment by kolekti** [comment]
alors c'est normal tant qu'il reste des fichiers locaux non envoyés kolekti propose le meme dialogue, ce qui permet de différencier des commit de lots de fichiers avec des messages différents. 
Si l'on ne sélectionne rien et qu'on valide (il faudrait griser le bouton de validation quand rien n'est sélectionné)
Je pense également ajouter une entrée "exclure ce fichier de la synchronisation" qui permettrait de créer un module ou une trame mais de ne pas l'envoyer sur svn.
