### ISSUE TITLE
Les versions ne s'affichent pas s'il n'y a pas de langues paramétrées

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#111]
Si on crée une version alors que les langues des versions (traductions) n'ont pas été définies, il est possible de cliquer sur la version mais celle-ci affiche un écran blanc, faisant penser à un bug.

Il faudrait ici un message qui invite à paramétrer les langues de versions

**Comment by kolekti** [comment]
Cette situation ne peut plus se produire depuis la correction du bug #64. Les langues sources sont toujours considérées comme langues de versions.
