### ISSUE TITLE
Affichage des sous-repertoires dans l'onglet Versions

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#113]
A partir d'un certain nombre de versions il est intéressant de pouvoir les répartir dans des sous-répertoires.

La création de sous-répertoire semble possible lors de la création de la version, en mettant [lenomdureperoire]/ avant le nom de la version.

Le repertoire est bien créé, mais n'apparait pas dans l'onglet Versions

**Comment by kolekti** [comment]
La présence de sous répertoires dans les versions n'est pas prévu par le moteur de publication; si on le supporte cela implique de retester l'ensemble des fonctions de publication de kolekti.

Je serais plus pour ne plus donner la possibilité de créer des dossier lors de la création d'une version

**Comment by vbdx** [comment]
Si on ne permet pas la création de sous-répertoires alors il faudrait offrir un peu de souplesse pour gérer l'affichage de dizaines de version. Aujourd'hui on ne peut modifier l'affichage de la liste que selon le nom et la date, ce qui me paraît limité.

Quelques idées :
- pouvoir renommer une version
- pouvoir archiver (zipper) une vielle version pour stockage ailleurs
- avoir un champ en haut qui permette de n'afficher que les versions qui contiennent les caractères saisis
