### ISSUE TITLE
Design des onglets de langues dans les versions

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#118]
Pour mieux différencier les langues en traduction, et leur différents états, le design ci-joit est proposé
![projetpictolangues](https://cloud.githubusercontent.com/assets/11272904/17246957/c245a490-558f-11e6-8d16-4ef511524195.png)

**Comment by kolekti** [comment]
De plus j'ai aligné à droite sur l'onglet l'ensemble des langues non actives, ce qui permet de plus facilement focaliser sur les onglets des langues initialisées, et permet facilement de créer la version dans un nouvelle langue.
