### ISSUE TITLE
Chemins non-génériques dans les assemblages

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#121]
Les assemblages actuels contiennent des URLs spécifiques à l'utilisateur qui les a créés. 
Conséquence : seul cet utilisateur peut ensuite générer des publications avec des hyperliens fonctionnels.

**Comment by kolekti** [comment]
A noter : les assemblages présents dans les versions doivent etre repris pour:
- reprendre urls présentes dans les topicinfo
- reprendre les liens qui n'ont pas été correctement traités lors de l'assemblage.
