### ISSUE TITLE
Ecrasement des publications en cas de "Tout publier"

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#125]
Dans les versions, s'il manque {LANG} dans :
- dans "Dossier de la publication" de la trame
- ou dans "Nom des fichiers publiés" de la sortie dans les paramètres de publication

alors les publications des différentes langues s'écrasent, seule la dernière langue est conservée.

Propositions :
- Message d'avertissement, lors du clic sur "Tout publier" qu'il n'y a pas de variable {LANG}
- Message d'alerte dès que Kolekti écrase des publications

Problème : à ce stade il est trop tard pour modifier les paramètres.

Donc faut-il alerter dès la création de la version ? Ou bien créer des répertoires de langues dans /releases/[nomdelarelease]/publications (au risque d'avoir un process différent de la publication des sources) ?

**Comment by kolekti** [comment]
Quelle serait la meilleure option du point de vue de l'utilisateur ?

**Comment by vbdx** [comment]
Après discussion, on opte pour la création automatique d'un dernier niveau de répertoire portant le code langue.
Au final, l'arborescence dans le repertoire publication sera : Dossier de publication (défini dans la trame) / Dossier (défini dans le profil) / Dossier code langue.
