### ISSUE TITLE
CKE : création d'élément vides suite à l'ajout de conditions

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#133]
Cas observé sur un élément dd d'une dl :
- passage en mode bloc
- clic sur C
- ajout de de condition et validation

En passant en mode source, on constate que 2 dd vides sont créés autour du dd modifié

**Comment by kolekti** [comment]
Le probleme se produit également si l'on n'insère pas de condition.
Des élements supplémentaires sont créés par CKEditor lors de l'ouverture de la vue source alors qu'une selection a été faite en mode block.

**Comment by kolekti** [comment]
Prévoir un garde-fou : desactiver le bouton "vue source" en mode bloc
