### ISSUE TITLE
Enregistrement des modifs dans Versions

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#16]
Chaque modif dans une version (changement de statut, activation du focus, demain ajout de commentaire, ...) doit entraîner l'affichage du bouton Enregistrer.

**Comment by kolekti** [comment]
Ces actions sont effectuées immédiatement, je suis ok que cela est pertubant pour l'utilisateur.
Il me vient une question, cette propriété (statut) est lié à chaque assemblage (chaque langue),

est ce que le bouton Enregistrer sauvegarde les modifications de toutes les langues ? ou seulement de l'assemblage courant ? Est il possible de changer d'onglet (langue) sans Enregistrer ?

**Comment by vbdx** [comment]
Pour moi le bouton Enregistrer doit sauvegarder les modifs de toutes les langues, c'est à l'échelle de la version qu'on raisonne.
On devrait pouvoir changer d'onglet sans devoir enregistrer, car en cas de modifs répétitives (ex : changer le statut de 5 langues) un enregistrement par onglet serait pénible.
