### ISSUE TITLE
Zip de l'ensemble des publications : manque nom de fichier

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#177]
Dans la fenêtre de résultat des publications, l'option "Zip de l'ensemble des publications" donne accès à un zip, mais sans nom (ce qui complique un peu les choses après).

![zipsansnom](https://user-images.githubusercontent.com/11272904/37704441-0c45279a-2cf9-11e8-8063-243acb18464c.png)

Il faudrait a minima lui donner un nom aléatoire, ou reprendre par exemple des éléments d'information de la trame, de la date, des paramètres, etc.

**Comment by sherpa-doc** [comment]
pour info cela fonctionne correctement dans les versions
