### ISSUE TITLE
Déplacement de section

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#2]
Dans la vue Trame, lorsque l'on monte ou descend une section, il arrive qu'elle entre dans une section existante, devenant ainsi une sous-section (avec impossibilité d'en sortir ensuite).
On s'attend plutôt à ce que la section que l'on déplace reste au même niveau, en "enjambeant" les sections existantes.

**Comment by kolekti** [comment]
Si l'action de descendre une section précédant immédiatement une autre section "saute" cette dernière section, il devient alors impossible de déplacer une section coome sous-section d'une autre.

Par contre l'action "monter" sur une sous-section présente en première position de la section parente devrait faire sortir cette sous-section de sa parente.

**Comment by vbdx** [comment]
La question est : va-t-on davantage utiliser Monter-Descendre pour : 
* Changer l'ordre des sections
* ou ré-organiser les sections (en regroupant certaines dans d'autres) ?

Dans le premier cas, il faut pouvoir sauter les sections existantes, car si on doit passer à travers 3 sections contenant chacune 10 modules, cela fait bcp de clics.

Dans le 2e cas, il faut effectivement pouvoir ressortir une sous-section par le haut, mais aussi par le bas.

à trancher ...

**Comment by kolekti** [comment]
Aujourd'hui c'est la deuxième hypothèse que nous avons retenu, effectivement cela fait beaucoup de clics pour réorganiser les sections.
Mon commit a réglé le probleme de la sortie de section (par le haut et le bas) 
Je pense que dans une version ultérieure il faut reconsidérer la possibilité de glisser /déposer les modules et les section dans la trame
