### ISSUE TITLE
Récupération des images et variables à traduire

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#204]
Dans une version, pour récupérer une image ou un fichier de variables à traduire, le clic droit sur un fichier + "Enregistrer la cible du lien sous..." ne fonctionne pas.

Suggestion : proposer dans Télécharger / Exporter des boutons Images et Variables qui créent des zips avec le contenus des repertoires

**Comment by kolekti** [comment]
fixé, de nombreuses améliorations dans les explorateurs
