### ISSUE TITLE
Bouton "rev" à coloriser

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#21]
Il serait utile de mettre sur le bouton "rev" (en haut à droite) un fond :
* orange quand des fichiers en local sont plus récents que ceux du référentiel (serveur)
* rouge quand des fichiers du référentiel sont plus récents que ceux en local

**Comment by vbdx** [comment]
Le vert correspond à quoi ?

**Comment by kolekti** [comment]
J'ai trouvé que les couleurs orange et rouge étaient inappropriéees pour un état normal de travail, il ne faut pas utiliser une couleir d'alerte si aucune condition anormale n'est rencontrée, du coup j'ai utilisé les couleurs suivantes :
 - blanc : tout est synchronisé
- vert : des modifications locales ont été effectuées
- bleu : des versions distantes sont disponibles
- orange : modifications concurrentes
- rouge : erreur à la synchro.
