### ISSUE TITLE
Paramétrage des langues à la création du projet

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#25]
Lors de la création d'un projet, on devrait pouvoir spécifier dans l'interface :
* la langue source
* les langues prévues pour la traduction

Ce sont 2 paramètres à dissocier, et à rendre modifiables la configuration du projet.

**Comment by kolekti** [comment]
Cela sera géré dans une interface dédiée aux administrateurs de projets, 
ces parametres sont stockés dans kolekti/settings.xml, 

- ajouter une langue source implique la création des dossiers topics, tocs, images dans le répertoire de la langue dans l'arborescence source.
- supprimer une langue ? quid des données ?
