### ISSUE TITLE
Insertion nouveau module depuis une trame

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#3]
Après avoir saisi le nom du module à créer, on s'attend à revenir directement sur la trame (avec le nouveau module à sa place), plutôt que sur une fenêtre intermédiaire d'exploration où l'on ne sait pas qu'il faut cliquer sur le nouveau module pour l'insérer.

**Comment by vbdx** [comment]
Devrait fonctionner aussi quand l'utilisateur oublie de spécifier l'extension du module (en ajoutant automatiquement l'extension .html)

**Comment by kolekti** [comment]
c'est fixé
