### ISSUE TITLE
Edition des métadonnées sous Firefox

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#40]
Apparemment cette fonction a une incidence (néfaste) sur l'enregistrement des modules. Elle est désactivée sur la version 0.7.0 mais devrait fonctionner sur la 0.7.1

**Comment by kolekti** [comment]
Le plugin metadonnées que j'avais développé a été abandonné, j'ai découvert que ckeditor avait un mode d'édition page complete, et un plugin d'édition des propriétés du document (titre; doctype; metadonnés). J'ai intégré ce mode

**Comment by vbdx** [comment]
Avec le nouveau plugin, quand on clique sur "propriétés", la meta-donnée "topic_file" présente dans le module n'est pas affichée dans la boite de dialogue Propriétés du document (onglet Metadonnées). 
A la place il y a une méta-donnée "topicfile" vide.
