### ISSUE TITLE
Erreur sur "Editer le fichier" (de paramètres de publication)

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#42]
Quand on crée une trame, le fichier de paramètres de publication n'est pas défini et un clic sur l'engrenage bleu affiche une page d'erreur "XMLSyntaxError at /settings/job".
Il faudra que cela affiche plutôt un message du type "Edition impossible, fichier non défini" ou "Définissez d'abord un fichier de paramètres" .

**Comment by kolekti** [comment]
Fix : l'engrenage bleu n'est plus visible lorsqu'aucun job n'est attaché à la trame, le manu à un intitulé "Sélectionnez...", et la zone de selection rapide est masquée.
