### ISSUE TITLE
Certaines balises d'index ne fonctionnent pas (sortie PDF)

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#55]
Visiblement cela dépend de la présence de texte à côté de la balise :

`<p><ins class="index">MotClé</ins>MotClé</p>`
fonctionne (produit une entrée d'index valide)

`<p><ins class="index">MotClé</ins></p>`
ne fonctionne pas (produit une entrée d'index non valide, avec une page "0")

**Comment by kolekti** [comment]
Princexml ne peut visiblement pas faire une référence sur un élément non affiché, le paragraphe contenant les marques d'index précédent un titre est dans ce cas.
De plus si on rétabli du contenu dans ce paragraphe, il est présenté la page précédente du titre.

Solution : le filtre xsl de pivot permet de réintégrer ces marques d'index dans le contenu du titre du module.
