### ISSUE TITLE
La trame ne s'enregistre pas si le nom d'un module comporte une apostrophe

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#57]
Constaté avec un module "03-Description de l'appareil.html"

C'est peut-être normal, dans ce cas quelle est la liste des signes à proscrire ?

Les espaces et les accents semblent passer correctement, mais faut-il conseiller de ne pas en utiliser ?

**Comment by kolekti** [comment]
Normalement, tous les signes valides sur le systeme de fichiers de l'os sous  lequel tourne kolekti devraient fonctionner, il vaut mieux donc proscrire / \ ? * : | < > ainsi que ' (limitation kolekti)

**Comment by vbdx** [comment]
L'info sera integrée dans la doc
