### ISSUE TITLE
Création module sans extension

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#6]
A la création d'un module, si on saisit juste le nom du module (sans extension), alors l'extension .html n'est pas ajoutée automatiquement et le picto à gauche du module (dans l'explorateur) est différent des modules normaux.

**Comment by kolekti** [comment]
La problématique est plus générale : 
Doit-on masquer les extensions de fichier dans l'interface ou non ? Soit l'utilisateur visualise et doit saisir les extensions des noms de fichier (partout dans l'interface), soit elles sont implicites. 

J'ai un préférence pour ne pas cacher les extensions et donc de demander à l'utilisateur de les saisir. Cependant il reste possible de contrôler que l'utilisateur a bien saisi une extension permise 

Les pictos des fichiers sont en effet dépendant de l'extension du nom de fichier.

**Comment by kolekti** [comment]
Lorsqu'un nom de module, mais aussi trame et fichier de parametres est donné sans extension, l'extension par défaut est ajoutée lors de la création de l'objet
