### ISSUE TITLE
comment créer un nouveau fichier de variables

### ISSUE THREAD

**Issue by kolekti** [kolekti/kolekti#60]
Pas de moyen simple dans l'interface de créer un nouveau fichier de variables

**Comment by vbdx** [comment]
Il faudrait mettre en cohérence le bouton Nouveau actuel (qu'il crée un tableau simple vide et non qu'il demande un fichier à importer), et créer un bouton "importer fichier ods" quelquepart.

**Comment by kolekti** [comment]
Le bouton Nouveau crée maintenant un fichier de variables vide, que l'on peut éditer dans l'interface directement.
Les actions d'import/export sont disponibles en regard de chacun des fichiers de variables dans le navigateur, ainsi il n'est plus nécessaire de garder la correspondance entre le nom de fichier ods importé et le nom de fichier de variable (par exemple, on peut très bien mettre à jour "mesvariables.xml" dans kolekti en important "mesvariables_12-09-2016 test.ods")

Mettre à jour l'aide en ligne kolekti  sur ce point
