### ISSUE TITLE
Manque class="WithPageRef" dans la sortie princexml

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#61]
Les références croisées ne sont pas identifiées par l'ajout d'un atttribut class spécifique, cela rend impossible la personnalisation des renvois aux pages dans les PDFs

**Comment by kolekti** [comment]
Cet attribute doit etre ajouté par le filtre prépublication appliqué préalablement sur le pivot, ce filtre est un xslt spécifique au projet, et présent dans le dossier kolekti/publication-templates/princexml/filters 

Note :  plusieurs fichiers peut exister dans ce dossier, il est possible de confiurer un filtre particulier pour une sortie particulière d'un parametrage de publication (partie script)

**Comment by vbdx** [comment]
On l'indiquera dans la doc
