### ISSUE TITLE
Indicateur de progression lors de l'enregistrement d'une version 

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#66]
Dans une version, lorsque l'on change le statut d'une langue (par exemple), le bouton Enregistrer s'allume, mais quand on clique dessus rien ne se passe. On a l'impression que la sauvegarde est impossible, alors qu'elle est bien en train de s'effectuer.
Il faudrait ajouter un indicateur d'activité ou de progression

**Comment by vbdx** [comment]
en fait, c'est le commit auto qui prend du temps, je pense qu'il faut le supprimer (comme on supprime le commit auto lors de l'initialisation d'un onglet de langue)

**Comment by kolekti** [comment]
Pas de modification d'interface pour l'enregistrement des versions,
Suppression de la synchro automatique lors du changement de status d'une langue
Ajout d'un spinner lors des opérations de synchro
