### ISSUE TITLE
Selection utilisateur aléatoire dans sortie WebHelp5

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#70]
Constaté sur un paragraphe comportant la condition :
OS = Linux , Mac ; F = docx
qui reste affiché dans l'aide en ligne alors qu'on modifie la sélection :
- OS = Mac
- F = docx

en :
- OS = Win7
- F = docx

**Comment by vbdx** [comment]
Important de savoir si c'est réparable ou pas, pour savoir si on poursuit cette piste

**Comment by kolekti** [comment]
il faudrait indiquer dans la doc quelle est la sémantique de l'expression `OS = Linux , Mac ; F = docx`

**Comment by kolekti** [comment]
purement logique si on a comme critères 
C1 et C2 avec valeurs possibles v1, v2, v3

on évalue une expression conditionnelle sur un élément, pour déterminer si l'élément doit être inclus dans la publication ou visible à l'écran (dans la cas du filtrage utilisateur) 

l'évaluation consiste à prendre en entrée un ensemble de valeur uniques (ou aucune valeur) pour chacun des critères utilisés dans l'expression.

on évalue l'expression : C1 = v1 vraie : 
- si la valeur exprimée est v1 pour ce critère dans le profil ou en selection uilisateur
- si la valeur n'est pas exprimée pour ce critère dans le profile.  

on évalue l'expression c1= v1, v2 vrai : 
- si la valeur exprimée est v1 ou v2 dans le profil ou la sel utilisateur
- si la valeur n'est pas exprimée (profil)

on évalue l'expression c1=v1; c2=v1 vrai : 
- si c1 vaut v1 ET c2 vaut v2
