### ISSUE TITLE
Ajout d'un champ "Nom" pour différencier les sorties dans la sélection rapide

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#73]
A l'instar des noms de profils (dans les paramètres de publication), il serait utile d'avoir des noms de sorties pour différencier, par exemple, 2 sorties princexml différentes

**Comment by kolekti** [comment]
Normalement c'est le cas tu peux spécifier le nom du fichier / dossier produit dans la partie script
Si tu ne la vois pas dans les anciens lancements il faut supprimer / recréer la sortie

Le 11 janvier 2016 16:53:06 GMT+01:00, Vincent Bidaux <notifications@github.com> a écrit :
>A l'instar des noms de profils (dans les paramètres de publication), il
>serait utile d'avoir des noms de sorties pour différencier, par
>exemple, 2 sorties princexml différentes
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kolekti/kolekti/issues/73

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by vbdx** [comment]
Il y a bien le champ "Nom des fichier publiés" qui est là, mais il manque à mon sens un champ "Nom de la sortie" pour spécifier le nom qui s'affiche dans la partie "Sélection rapide" à droite de la trame

**Comment by kolekti** [comment]
Implémenté, appliquer la fixture 73 aux projets : ajout de l'élément label aux sorties des parametres de publication existants dans les projets.
