### ISSUE TITLE
Pouvoir surcharger criteria.css

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#74]
Il serait utile de pouvoir utiliser une autre feuille de style pour spécialiser l'affichage des modules dans la trame (dépliée), en surchargeant la feuille criteria.css générée par défaut.

Suggestion de nom : /kolekti/UI-stylesheets/topic_inTOC.css

**Comment by kolekti** [comment]
implémenté, le chemin de la feuille de style dans le projet est : 
/kolekti/ui-stylesheets/toc.css
la feuille de style s'applique à la trame entière, il est conseillé d'utilliser la pseudo classe .topiccontent dans les selecteurs pour cibler le contenu des topic et ne pas interférer avec les autres éléments d'interface de l'éditeur de trames

**Comment by kolekti** [comment]
A reprendre dans la doc
