### ISSUE TITLE
Faciliter le retour à la trame depuis le fichier de paramères

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#78]
Quand on clique sur l'engrenage bleu à droite de la trame pour ouvrir le fichier de paramètres actif, le contenu du fichier de paramètre vient remplacer complètement la trame, et il est difficile d'imaginer qu'il faut utiliser la fèche "Page précédente" du navigateur pour revenir à la trame.

Il faudrait trouver un moyen parmi les suivants, qui reste en accord avec les bonnes pratiques des applis web :
* ajouter un bouton "retour" plus explicite dans la barre de menu
* afficher un fil d'ariane (historique des pages visitées). Dans ce cas, il faudrait bien le disttinguer de l'autre fil d'Ariane (emplacement des documents dans l'arborescence) que l'on trouve dans les explorateurs.
* ouvrir le fichier de paramètre dans une fenêtre modale

**Comment by kolekti** [comment]
Le bouton retour (placé à droite des titres de pages) a été implémenté
