### ISSUE TITLE
Créer menu Paramètres

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#84]
Actuellement sont regroupés dans Outils tout ce qu'on ne voulait pas voir au premier niveau, mais cela ne sighnifie pas pour autant qu'il s'agit toujours d'outils...

* Créer un menu Paramètres (à droite d'Outils) comprenant : Critères, Variables, Paramètres de publication
* Conserver dans Outils : Synchronisation, Import

Voir où on met "Projets" : la page cible permet aujourd'hui de sélectionner le projet actif, et de paramétrer les langues. Donc plutôt dans "Paramètres" ?

**Comment by kolekti** [comment]
Je mettrais plutot projets dans Outils, car il donne accès au gestionnaire de projets, alors que les paramètres se contonnent plutot au projet en cours

**Comment by kolekti** [comment]
Plutot que d'introduire un nouveau menu, j'ai regroupé les outils et parametres dans un menu unique avec séparateurs en mettant en avant les parametres du projet (critères, variables, langues, param publication) puis les outils plus généraux (synchro, gestionnaire de projets)
