### ISSUE TITLE
Ajouter un bouton "Tout publier" (les traductions d'une version)

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#88]
Dans le cas (relativement rare, mais quand même) où une modification mineure nécessite la republication de toutes les traductions d'une version, il serait utile d'avoir un bouton qui le permette, plutôt que de devoir publier chaque onglet à la suite.

**Comment by kolekti** [comment]
Faut-il considérer le status de la langue pour la publication ?

**Comment by vbdx** [comment]
Non, juste ignorer les langues qui ne sont pas créées (ex : ja, tr et zh dans l'image de #118 )

**Comment by kolekti** [comment]
Ajout d'une option "Publier toutes les langues" dans le bouton "Publier" dans les versions.
