### ISSUE TITLE
Remonter d'un niveau dans les explorateurs

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#89]
Dans un explorateur (de trames, de modules, d'images), quand on accède à un sous-répertoire, le bouton précédent du navigateur ramène à l'onglet précédent et non pas au répertoire supérieur

**Comment by kolekti** [comment]
le bouton retour du navigateur retourne maintenant à l'écran précédent.
NB. l'écran précédent n'est pas nécessairement le répertoire de niveau supérieur, dans le cas d'un clic sur  le chemin d'accès pour remonter)
