### ISSUE TITLE
Les langues de traduction ne sont pas considérées comme des langues officielles (pour les variables)

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#94]
Dans les tableaux de variables, les lignes qui contiennent des critères ont un fond rouge lorsque le crtière n'est pas déclaré dans les paramètres du projet.

Dans le cas (rare) où l'on doit utiliser le critère LANG avec toutes les valeurs possibles, seule la langue source du projet apparaît sur fond bleu (normal), toutes les autres apparaissent sur fond rouge.

![languestraduitesdansvariables](https://cloud.githubusercontent.com/assets/11272904/13171381/d1935b48-d6f2-11e5-887a-694df0675b5a.png)

Cela pose un problème pour la modification et l'enregistrement en ligne du tableau de variables

**Comment by kolekti** [comment]
Les variables ne doivent pas utiliser le critère LANG : depuis kolekti 0.7 nous avons un fichier de variables par langue, les variables de la langue source sont dans les sources, et les traductions sont dans les dossiers variables des langues respectives.

**Comment by vbdx** [comment]
Oui, mais il peut y avoir 2 cas particuliers qui nécessitent l'utilisation du crtière LANG dans un fichier de variables situé dans /share:
- les valeurs d'un critère ont un sens différent selon la langue, et donc ne peuvent entrer dans un processus classique de traduction. Exemple : &NomDuRelecteur : John (en), Laurent (fr), José (es) , etc.
- On ne veut pas que certains critères passent par le processus de traduction (qui fait intervenir plusieurs acteurs, et une mémoire de traduction sujette à variations).

**Comment by vbdx** [comment]
Il serait utile de permettre quand même d'enregistrer le tableau (éventuellement avec un message d'avertissement).
Cela éviterait de devoir passer systématiquement par l'export-import d'ods

**Comment by kolekti** [comment]
les langues des releases sont valides.
