### ISSUE TITLE
Compatibilité 0.7.1 avec anciennes releases

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#96]
Les nouveautés apportées par la version 0.7.1 dans l'onglet Versions (ex : pas de statut sur la langue source) ne sont pas visibles sur les releases générées en version 0.7.0e.

**Comment by kolekti** [comment]
0.7.1 utilise une information qui n'était pas présente dans les release générées précédement : la langue à partir de laquelle une langue est générée. 
Une fixture n'est pas possible car cette information ne peut etre déterminée automatiquement dans les releases pré-0.7.1.

Il est donc nécessaire d'ajouter manuellement la propriété svn release-srclang sur les assemblages des versions antérieures à 0.7.1

**Comment by vbdx** [comment]
La propriété svn à ajouter est : release_srclang

Avec comme valeur le code de la langue à partir de laquelle a été créée la version.

Note : pas de propriété release_srclang sur la langue source de la version.

**Comment by kolekti** [comment]
Il faut utiliser les fixtures pour faire évoluer les propriétés des releases quand c'est nécessaire.
