### ISSUE TITLE
"Vos modifications" affiche les modifications d'autres projets

### ISSUE THREAD

**Issue by vbdx** [kolekti/kolekti#98]
Sur l'écran d'accueil, la zone "Vos modifications" liste les dernières modifications indépendamment du projet actif. Il serait pertinent de n'avoir que les modifications relatives au projet en cours.

**Comment by vbdx** [comment]
Les modifs "hors-projet" affichent un écran jaune quand on clique dessus.

**Comment by kolekti** [comment]
Résolu dans la 0.7.2
